#!/bin/bash
#================================================================
#
#          FILE:  sha_test.sh
# 
#         USAGE:  ../make run-test
# 
#   DESCRIPTION:  Test suite for sha1 project.  Simple script
#                 designed to test the output of sechash with the
#                 output of sha1sum (if installed).  The test
#                 simply outputs each 160-bit hash to stdout for
#                 visual comparison.
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  Script requires 'sha1sum' to be installed to
#                 generate the authoritative output to compare 
#
#                 This script is not written to run in the test/
#                 directory, it written to run in the parent
#                 directory by running: make run-test
#
#          BUGS:  ---
#         NOTES:  Currently, the script only outputs the 160-bit
#                 hash of *.txt files located in the test/
#                 directory.  It can be easily modified to hash
#                 other files types.
#
#        AUTHOR:  Jason S. Jones (), jsjones96@gmail.com
#       COMPANY:  
#       VERSION:  1.0
#       CREATED:  12/09/2010 08:39:04 PM PST
#      REVISION:  ---
#================================================================

syssha1=$(which sha1sum)

echo ""
echo "*** Test suite to verify the 160-bit hash *** "
echo ""
echo "'sha1    -->' is the hash generated by this program"
echo "'sha1sum -->' is the hash generated by the sha1sum program that is"
echo "   included with just about all linux distributions."
echo "=================================================================="


if [ ! -e ./sha1 ] ; then
    echo "sha1 does not exist; need to run 'make' before 'make run-test'"
    exit 1;
fi


for file in test/*.txt;
do
    echo -n "sha1     -->  "
    ./sha1 $file

    if [ ! -z $syssha1 ] ; then
        echo -n "sha1sum  -->  "
        $syssha1 $file
    else
        echo -n "Unable to locate the system sha1sum program."
    fi

    echo ""
done
