#!/bin/bash
#================================================================
#
#          FILE:  sha_test.sh
# 
#         USAGE:  ../make run-test
# 
#   DESCRIPTION:  Test suite for sec-hash project.  Simple script
#                 designed to test the output of sechash with the
#                 output of sha1sum (if installed).  The test
#                 simply outputs each 160-bit hash to stdout for
#                 visual comparison.
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  Script requires 'sha1sum' to be installed to
#                 generate the authoritative output to compare 
#
#                 This script is not written to run in the tests/
#                 directory, it written to run in the parent
#                 directory by running: make run-test
#
#          BUGS:  ---
#         NOTES:  Currently, the script only outputs the 160-bit
#                 hash of *.txt files located in the tests/
#                 directory.  It can be easily modified to hash
#                 other files types.
#
#        AUTHOR:  Jason S. Jones (), jsjones96@gmail.com
#       COMPANY:  J2Labs
#       VERSION:  1.0
#       CREATED:  12/09/2010 08:39:04 PM PST
#      REVISION:  ---
#================================================================

echo ""
echo "Test suite to verify the 160-bit hash generated by sechash."
echo "=========================================================="


if [ ! -e ./sechash ] ; then
    echo "sechash does not exist; need to run 'make' before 'make run-test'"
    exit 1;
fi


for file in tests/*.txt;
do
    echo -n "sec-hash -->  "
    ./sechash $file

    echo -n "sha1sum  -->  "
    /usr/bin/sha1sum $file

    echo ""
done
