./" Process this file with
./" groff -man -Tascii sha1.1
.TH SEC-HASH 1 "NOVEMBER 2010" "sec-hash version 0.1" "User Manual"

.SH NAME
sec-hash \- secure hash algorithm (sha1)

.SH SYNOPSIS
.B sec-hash 
.I filename
.B[
.I filename
.B]

.SH DESCRIPTION
.B sec-hash
is an implementation of the sha1 secure hash algorithm.

.SH AUTHOR
Jason Jones <jsjones96@gmail.com>
