./" Process this file with
./" groff -man -Tascii sha1.1
.TH SHA1 1 "NOVEMBER 2010" "sha1 version 0.1" "User Manual"

.SH NAME
sha1 \- secure hash algorithm (sha1)

.SH SYNOPSIS
.B sha1 
.I filename
.B[
.I filename
.B]

.SH DESCRIPTION
.B sha1
is an implementation of the sha1 secure hash algorithm.

.SH AUTHOR
Jason Jones <jsjones96@gmail.com>
